/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { CreditGrantRequest, CreditGrantResponse, ProblemDetails } from './..';

/**
 * @summary Grants credits to a user.
 */
export const postApiAdminCreditsGrants = (
  creditGrantRequest: CreditGrantRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<CreditGrantResponse>> => {
  return axios.default.post(`/api/admin/credits/grants`, creditGrantRequest, options);
};

export const getPostApiAdminCreditsGrantsMutationOptions = <
  TError = AxiosError<CreditGrantResponse | ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAdminCreditsGrants>>,
    TError,
    { data: CreditGrantRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAdminCreditsGrants>>,
  TError,
  { data: CreditGrantRequest },
  TContext
> => {
  const mutationKey = ['postApiAdminCreditsGrants'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAdminCreditsGrants>>,
    { data: CreditGrantRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAdminCreditsGrants(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAdminCreditsGrantsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAdminCreditsGrants>>
>;
export type PostApiAdminCreditsGrantsMutationBody = CreditGrantRequest;
export type PostApiAdminCreditsGrantsMutationError = AxiosError<CreditGrantResponse | ProblemDetails>;

/**
 * @summary Grants credits to a user.
 */
export const usePostApiAdminCreditsGrants = <
  TError = AxiosError<CreditGrantResponse | ProblemDetails>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAdminCreditsGrants>>,
      TError,
      { data: CreditGrantRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAdminCreditsGrants>>,
  TError,
  { data: CreditGrantRequest },
  TContext
> => {
  return useMutation(getPostApiAdminCreditsGrantsMutationOptions(options), queryClient);
};
