/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { ProblemDetails } from './..';

/**
 * @summary Deletes all user-owned data and all data obtained from or derived from Google/YouTube APIs.
The authenticated user's account is marked as deleted, preserving only the minimal technical identity row.
After deletion, auth cookies are cleared and the user must log in again to use the app.
 */
export const deleteApiUsersMe = (options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/users/me`, options);
};

export const getDeleteApiUsersMeMutationOptions = <TError = AxiosError<ProblemDetails>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiUsersMe>>, TError, void, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiUsersMe>>, TError, void, TContext> => {
  const mutationKey = ['deleteApiUsersMe'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiUsersMe>>, void> = () => {
    return deleteApiUsersMe(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiUsersMeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiUsersMe>>>;

export type DeleteApiUsersMeMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Deletes all user-owned data and all data obtained from or derived from Google/YouTube APIs.
The authenticated user's account is marked as deleted, preserving only the minimal technical identity row.
After deletion, auth cookies are cleared and the user must log in again to use the app.
 */
export const useDeleteApiUsersMe = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiUsersMe>>, TError, void, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiUsersMe>>, TError, void, TContext> => {
  return useMutation(getDeleteApiUsersMeMutationOptions(options), queryClient);
};
