/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  AuthMeResponse,
  GetApiAuthLoginGoogleParams,
  GetApiAuthLoginGoogleWriteParams,
  GetApiAuthLogoutParams,
} from './..';

export const getApiAuthLoginGoogle = (
  params?: GetApiAuthLoginGoogleParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.get(`/api/auth/login/google`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiAuthLoginGoogleQueryKey = (params?: GetApiAuthLoginGoogleParams) => {
  return [`/api/auth/login/google`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthLoginGoogleQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogle>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthLoginGoogleQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthLoginGoogle>>> = ({ signal }) =>
    getApiAuthLoginGoogle(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthLoginGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthLoginGoogle>>>;
export type GetApiAuthLoginGoogleQueryError = AxiosError<unknown>;

export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | GetApiAuthLoginGoogleParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogle>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogle>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLoginGoogle>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogle>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiAuthLoginGoogle<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogle>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogle>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiAuthLoginGoogleQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Starts the explicit Google write-consent flow.
 */
export const getApiAuthLoginGoogleWrite = (
  params?: GetApiAuthLoginGoogleWriteParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.get(`/api/auth/login/google/write`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiAuthLoginGoogleWriteQueryKey = (params?: GetApiAuthLoginGoogleWriteParams) => {
  return [`/api/auth/login/google/write`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthLoginGoogleWriteQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleWriteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthLoginGoogleWriteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>> = ({ signal }) =>
    getApiAuthLoginGoogleWrite(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthLoginGoogleWriteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>>;
export type GetApiAuthLoginGoogleWriteQueryError = AxiosError<unknown>;

export function useGetApiAuthLoginGoogleWrite<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | GetApiAuthLoginGoogleWriteParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthLoginGoogleWrite<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleWriteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthLoginGoogleWrite<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleWriteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Starts the explicit Google write-consent flow.
 */

export function useGetApiAuthLoginGoogleWrite<
  TData = Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLoginGoogleWriteParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLoginGoogleWrite>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiAuthLoginGoogleWriteQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Logs out the user and redirects to a specified return URL.
 */
export const getApiAuthLogout = (
  params?: GetApiAuthLogoutParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.get(`/api/auth/logout`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiAuthLogoutQueryKey = (params?: GetApiAuthLogoutParams) => {
  return [`/api/auth/logout`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuthLogoutQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthLogout>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiAuthLogoutParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLogout>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthLogoutQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthLogout>>> = ({ signal }) =>
    getApiAuthLogout(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthLogout>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthLogoutQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthLogout>>>;
export type GetApiAuthLogoutQueryError = AxiosError<unknown>;

export function useGetApiAuthLogout<TData = Awaited<ReturnType<typeof getApiAuthLogout>>, TError = AxiosError<unknown>>(
  params: undefined | GetApiAuthLogoutParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLogout>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLogout>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLogout>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthLogout<TData = Awaited<ReturnType<typeof getApiAuthLogout>>, TError = AxiosError<unknown>>(
  params?: GetApiAuthLogoutParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLogout>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthLogout>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthLogout>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthLogout<TData = Awaited<ReturnType<typeof getApiAuthLogout>>, TError = AxiosError<unknown>>(
  params?: GetApiAuthLogoutParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLogout>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Logs out the user and redirects to a specified return URL.
 */

export function useGetApiAuthLogout<TData = Awaited<ReturnType<typeof getApiAuthLogout>>, TError = AxiosError<unknown>>(
  params?: GetApiAuthLogoutParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthLogout>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiAuthLogoutQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiAuthMe = (options?: AxiosRequestConfig): Promise<AxiosResponse<AuthMeResponse>> => {
  return axios.default.get(`/api/auth/me`, options);
};

export const getGetApiAuthMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetApiAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthMe>>> = ({ signal }) =>
    getApiAuthMe({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthMe>>>;
export type GetApiAuthMeQueryError = AxiosError<unknown>;

export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = AxiosError<unknown>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
