/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { CreditActionCosts, CreditBalanceResponse, ProblemDetails } from './..';

/**
 * @summary Gets the current credit balance for the authenticated user.
 */
export const getApiCreditsBalance = (options?: AxiosRequestConfig): Promise<AxiosResponse<CreditBalanceResponse>> => {
  return axios.default.get(`/api/credits/balance`, options);
};

export const getGetApiCreditsBalanceQueryKey = () => {
  return [`/api/credits/balance`] as const;
};

export const getGetApiCreditsBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCreditsBalance>>,
  TError = AxiosError<ProblemDetails>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsBalance>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiCreditsBalanceQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCreditsBalance>>> = ({ signal }) =>
    getApiCreditsBalance({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCreditsBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCreditsBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCreditsBalance>>>;
export type GetApiCreditsBalanceQueryError = AxiosError<ProblemDetails>;

export function useGetApiCreditsBalance<
  TData = Awaited<ReturnType<typeof getApiCreditsBalance>>,
  TError = AxiosError<ProblemDetails>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsBalance>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCreditsBalance>>,
          TError,
          Awaited<ReturnType<typeof getApiCreditsBalance>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiCreditsBalance<
  TData = Awaited<ReturnType<typeof getApiCreditsBalance>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsBalance>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCreditsBalance>>,
          TError,
          Awaited<ReturnType<typeof getApiCreditsBalance>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiCreditsBalance<
  TData = Awaited<ReturnType<typeof getApiCreditsBalance>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsBalance>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Gets the current credit balance for the authenticated user.
 */

export function useGetApiCreditsBalance<
  TData = Awaited<ReturnType<typeof getApiCreditsBalance>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsBalance>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiCreditsBalanceQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Gets the current costs for credit actions.
 */
export const getApiCreditsCosts = (options?: AxiosRequestConfig): Promise<AxiosResponse<CreditActionCosts>> => {
  return axios.default.get(`/api/credits/costs`, options);
};

export const getGetApiCreditsCostsQueryKey = () => {
  return [`/api/credits/costs`] as const;
};

export const getGetApiCreditsCostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCreditsCosts>>,
  TError = AxiosError<ProblemDetails>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsCosts>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiCreditsCostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCreditsCosts>>> = ({ signal }) =>
    getApiCreditsCosts({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCreditsCosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiCreditsCostsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCreditsCosts>>>;
export type GetApiCreditsCostsQueryError = AxiosError<ProblemDetails>;

export function useGetApiCreditsCosts<
  TData = Awaited<ReturnType<typeof getApiCreditsCosts>>,
  TError = AxiosError<ProblemDetails>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsCosts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCreditsCosts>>,
          TError,
          Awaited<ReturnType<typeof getApiCreditsCosts>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiCreditsCosts<
  TData = Awaited<ReturnType<typeof getApiCreditsCosts>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsCosts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCreditsCosts>>,
          TError,
          Awaited<ReturnType<typeof getApiCreditsCosts>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiCreditsCosts<
  TData = Awaited<ReturnType<typeof getApiCreditsCosts>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsCosts>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Gets the current costs for credit actions.
 */

export function useGetApiCreditsCosts<
  TData = Awaited<ReturnType<typeof getApiCreditsCosts>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCreditsCosts>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiCreditsCostsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
