/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */

/**
 * Response DTO for credit action cost query
 */
export interface CreditActionCosts {
  copyTemplateExecuted: number;
  videoDetailsSubmitted: number;
  aiReplyGenerated: number;
  replyPostedToYouTube: number;
  aiTitle: number;
  aiDescription: number;
  aiTags: number;
  aiPlaylist: number;
}
