/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import type { CategoryDto } from './categoryDto';
import type { PlaylistDto } from './playlistDto';

export interface VideoDetailsDto {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  tags: string[];
  isAiTitleInProgress: boolean;
  isAiDescriptionInProgress: boolean;
  isAiTagsInProgress: boolean;
  isAiPlaylistSuggestionInProgress: boolean;
  playlists: PlaylistDto[];
  category?: CategoryDto;
  /** @nullable */
  defaultLanguage?: string | null;
  /** @nullable */
  defaultAudioLanguage?: string | null;
}
