/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { PlaylistDto, ProblemDetails } from './..';

/**
 * @summary Returns playlists for the current channel.
 */
export const getApiPlaylists = (options?: AxiosRequestConfig): Promise<AxiosResponse<PlaylistDto[]>> => {
  return axios.default.get(`/api/playlists`, options);
};

export const getGetApiPlaylistsQueryKey = () => {
  return [`/api/playlists`] as const;
};

export const getGetApiPlaylistsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPlaylists>>,
  TError = AxiosError<ProblemDetails>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlaylists>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPlaylistsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlaylists>>> = ({ signal }) =>
    getApiPlaylists({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPlaylists>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPlaylistsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlaylists>>>;
export type GetApiPlaylistsQueryError = AxiosError<ProblemDetails>;

export function useGetApiPlaylists<
  TData = Awaited<ReturnType<typeof getApiPlaylists>>,
  TError = AxiosError<ProblemDetails>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlaylists>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlaylists>>,
          TError,
          Awaited<ReturnType<typeof getApiPlaylists>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiPlaylists<
  TData = Awaited<ReturnType<typeof getApiPlaylists>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlaylists>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlaylists>>,
          TError,
          Awaited<ReturnType<typeof getApiPlaylists>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiPlaylists<
  TData = Awaited<ReturnType<typeof getApiPlaylists>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlaylists>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Returns playlists for the current channel.
 */

export function useGetApiPlaylists<
  TData = Awaited<ReturnType<typeof getApiPlaylists>>,
  TError = AxiosError<ProblemDetails>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlaylists>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiPlaylistsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
