/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Tubester API
 * To access protected endpoints, first log in:

[🔐 read only Login with Google](/api/auth/login/google?returnUrl=/swagger/index.html)

[🔐 write Login with Google](/api/auth/login/google/write?returnUrl=/swagger/index.html)
 * OpenAPI spec version: v1
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { ChannelDto, ChannelSyncResult, ProblemDetails } from './..';

/**
 * @summary Pulls channel details from YouTube and stores or updates the local channel snapshot.
 */
export const postApiChannelsPull = (options?: AxiosRequestConfig): Promise<AxiosResponse<ChannelDto>> => {
  return axios.default.post(`/api/channels/pull`, undefined, options);
};

export const getPostApiChannelsPullMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsPull>>, TError, void, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsPull>>, TError, void, TContext> => {
  const mutationKey = ['postApiChannelsPull'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiChannelsPull>>, void> = () => {
    return postApiChannelsPull(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiChannelsPullMutationResult = NonNullable<Awaited<ReturnType<typeof postApiChannelsPull>>>;

export type PostApiChannelsPullMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Pulls channel details from YouTube and stores or updates the local channel snapshot.
 */
export const usePostApiChannelsPull = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsPull>>, TError, void, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiChannelsPull>>, TError, void, TContext> => {
  return useMutation(getPostApiChannelsPullMutationOptions(options), queryClient);
};
/**
 * @summary Immediately synchronizes the current channel for the currently signed-in user.
The current channel is resolved from the channel context (yt_channel_id claim).
 */
export const postApiChannelsSyncCurrent = (options?: AxiosRequestConfig): Promise<AxiosResponse<ChannelSyncResult>> => {
  return axios.default.post(`/api/channels/sync/current`, undefined, options);
};

export const getPostApiChannelsSyncCurrentMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsSyncCurrent>>, TError, void, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsSyncCurrent>>, TError, void, TContext> => {
  const mutationKey = ['postApiChannelsSyncCurrent'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiChannelsSyncCurrent>>, void> = () => {
    return postApiChannelsSyncCurrent(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiChannelsSyncCurrentMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiChannelsSyncCurrent>>
>;

export type PostApiChannelsSyncCurrentMutationError = AxiosError<ProblemDetails>;

/**
 * @summary Immediately synchronizes the current channel for the currently signed-in user.
The current channel is resolved from the channel context (yt_channel_id claim).
 */
export const usePostApiChannelsSyncCurrent = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiChannelsSyncCurrent>>, TError, void, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiChannelsSyncCurrent>>, TError, void, TContext> => {
  return useMutation(getPostApiChannelsSyncCurrentMutationOptions(options), queryClient);
};
